### ISSUE TITLE
スタンプ数が多い場合にフロントでエラーが発生している

### ISSUE THREAD

**Issue by yuta-ike** [osushi-academy/sushi-chat#256]
## 概要
- スタンプを大量に描画するとフロントの挙動がおかしくなる
  - idなんとかっていうエラーがブラウザのコンソールに表示される 

## やること
実用上問題があるのかを含めて検討
問題がある場合は修正

**Comment by KoukiNAGATA** [comment]
これ、idの型のエラーは直したので(#317)、サーバーからたくさん送信してみて大丈夫そうならcloseで
