### ISSUE TITLE
DBのupdated_atカラムが更新される様にする

### ISSUE THREAD

**Issue by TOMOFUMI-KONDO** [osushi-academy/sushi-chat#494]
いくつかのマスタテーブルに`updated_at`カラムがあるが、レコードINSERT時に設定されるだけで更新されない状態になっている。

**Comment by Eri-0910** [comment]
https://to-c.hatenablog.com/entry/2017/04/17/225826
こういうのでやるか、updateクエリ叩くときにnode側で今の時刻取って更新することにするか？
@TOMOFUMI-KONDO
