### ISSUE TITLE
画面幅が小さいときにAdminToolが表示されない

### ISSUE THREAD

**Issue by yuta-ike** [osushi-academy/sushi-chat#517]

**Comment by KoukiNAGATA** [comment]
## 現状
AdminToolのレスポンシブ対応ができておらず、暫定対応として一定以下の幅だとAdminToolを表示しないようになっている

## 対応
表示しない代わりにAdminToolを表示するためのバナーを設置するなど、狭い画面幅でもAdminToolを操作できるようにする
