### ISSUE TITLE
AdminToolのツールチップ改善

### ISSUE THREAD

**Issue by yuta-ike** [osushi-academy/sushi-chat#518]
## 概要
AdminToolのボタンにツールチップを表示しているが、ブラウザのデフォルトのツールチップだと表示まで時間がかかるので、ライブラリを入れて目立つようにしたい。
![image](https://user-images.githubusercontent.com/38308823/134942510-48c7d926-2572-4c89-b2d2-5d2c3718871e.png)

## 動機
再生・一時停止ボタンは初見だと理解しづらいと思われるので、ツールチップで改善する

**Comment by KoukiNAGATA** [comment]
それなりに星ついてる(500 stars)し、これつかってみる
https://github.com/kabbouchi/vue-tippy
だめそうなら本家tippyつかう(9.6k stars)
https://github.com/atomiks/tippyjs

reactのwrapperはofficialやけど、vueのはunofficialな個人のものしか出てこなかった
まあ軽量・簡単なライブラリやし大丈夫でしょ
