### ISSUE TITLE
urlを開く以前のスタンプ数を持てていない

### ISSUE THREAD

**Issue by KoukiNAGATA** [osushi-academy/sushi-chat#590]
接続後に送信されたスタンプ数しか保持できていないため。
<img width="627" alt="Screen Shot 2021-10-19 at 0 27 57" src="https://user-images.githubusercontent.com/38304075/137764200-173c4cca-35d2-4135-a680-82704f1b27fd.png">

**Comment by yuta-ike** [comment]
API仕様を変更する必要あり。

**Comment by Eri-0910** [comment]
どっちも大した量じゃないと思うので(ほんと？)フロント含めて巻き取ります
