### ISSUE TITLE
[home]タイムスタンプの桁数が最大になると改行が入る

### ISSUE THREAD

**Issue by KoukiNAGATA** [osushi-academy/sushi-chat#608]
## 症状
桁数が多いタイムスタンプで、Chromeのフルスクリーン表示でも改行が入ってしまった。
10月中旬にならないと気づかないタイプのバグ。
## スクリーンショット
<img width="876" alt="Screen Shot 2021-10-24 at 13 12 58" src="https://user-images.githubusercontent.com/38304075/138580470-1e7ebdb2-6a6a-4209-b2de-1eab463a4b1e.png">

**Comment by yuta-ike** [comment]
`yyyy/MM/dd hh:mm`が入るように幅を調整するで良さそう
