### ISSUE TITLE
メッセージの送信に失敗した場合にダイアログが出てしまう

### ISSUE THREAD

**Issue by yuta-ike** [osushi-academy/sushi-chat#643]
メッセージの送信失敗時に、#619 で実装したUIが表示されるはずだがダイアログが出てしまう

https://discord.com/channels/825706990343815188/835804887274881024/923202880670932992

![image](https://user-images.githubusercontent.com/38308823/147475376-d34c5a73-0044-4a98-8488-3b558e55faf8.png)

**Comment by yuta-ike** [comment]
https://github.com/osushi-academy/sushi-chat/pull/619
で修正ずみ

**Comment by yuta-ike** [comment]
https://github.com/osushi-academy/sushi-chat/pull/619
で修正済みだがなぜかダイアログが出るケースがあるらしいので調査

**Comment by KoukiNAGATA** [comment]
`chatRoom.vue` の`window.alert("メッセージの送信に失敗しました")` が出ている。  
UIを作ったのでこちらは不要？

**Comment by yuta-ike** [comment]
不要だわ。
不要だけど`postMessage`とかってChatItemStore内でtry-catchしてるから、ChatRoom.vueでエラーは出ない気がするんだけど、なんでwindow.alertが実行されてるんだろう。。。。。。。

**Comment by yuta-ike** [comment]
現時点では確認されていないので、`window.alert`を削除する対応だけしておく
