### ISSUE TITLE
運営のコメント送信が常に失敗する

### ISSUE THREAD

**Issue by yuta-ike** [osushi-academy/sushi-chat#669]
メッセージが送信失敗する
リアクションも送れていない

**Comment by KoukiNAGATA** [comment]
メッセージ送信が成功するときもある

**Comment by KoukiNAGATA** [comment]
storeを書き換えてホットリロードが走った後は成功
その後Chromeをリロードすると失敗した
この辺に原因があるかも？

**Comment by KoukiNAGATA** [comment]
複数窓で管理者を開いたらバグる？

**Comment by yuta-ike** [comment]
フロントでルームにアクセスした状態でサーバーを立て直すと、立て直した後の管理者の投稿が失敗するんだけど、関係あるかな。
これが原因だったとしたら割とエッジケースだと思うから対応すべきか微妙な気がしてる

**Comment by KoukiNAGATA** [comment]
それだと通常ユーザーも投稿失敗するし、関係なさそう

**Comment by KoukiNAGATA** [comment]
```
POST_CHAT_ITEM:ErrorWithCode: User(ID) was not found.
```
が管理者のみ出る

**Comment by yuta-ike** [comment]
あーそうか。

**Comment by yuta-ike** [comment]
うーん、今 #643 の調査でdevelopをいじってるんだけど、管理者だけ失敗するのが再現しないなぁ。（#643 も再現しない
）

**Comment by yuta-ike** [comment]
複数窓で開くと失敗するの確認できた！

**Comment by KoukiNAGATA** [comment]
サーバー側が原因なのかな？わからん...

**Comment by TOMOFUMI-KONDO** [comment]
普通にルーム作って管理者からメッセージ送ったら送信失敗するの再現できた

**Comment by TOMOFUMI-KONDO** [comment]
実際 `hcD8EaWNrxGi9melAAAF` のユーザーはいなくて、DBにいたAdminユーザーは `9KN16lrapWsSGAe_AAAB`だった。
ID間違って二回発行されてる？

**Comment by yuta-ike** [comment]
SocketIOの挙動とかと関係するかも？複窓で開いた時とかリロードした時とかにconnection idが変わるとか変わらないとか、その辺が想定と食い違ってる説。

**Comment by TOMOFUMI-KONDO** [comment]
リロードしたら送信できた

**Comment by TOMOFUMI-KONDO** [comment]
```
// デバッグ用
    if (process.env.NODE_ENV !== "production") {
      socket.use(async ([eventName, data], next) => {
        if (socket.handshake.auth.token != null) {
          const { adminId } = await new AdminAuth().verifyIdToken(
            socket.handshake.auth.token,
          )
          console.log(eventName, adminId, data)
        } else {
          console.log(eventName, data)
        }
        next()
      })
    }
```

ここから出てたっぽい。これいるのかな。

**Comment by TOMOFUMI-KONDO** [comment]
運営窓開いてて、別の窓開くと元の運営窓でメッセージ送信失敗になるっぽい。池奥さんが言ってたコネクションID周りの話が当たってそう

**Comment by yuta-ike** [comment]
> ここから出てたっぽい。これいるのかな。

僕がデバッグで追加して放置してしまったやつかも。。。。。すまぬ。。。。。。。
